services:
  front:
    build: .
    image: ohmygoatsemifir/angular:latest
    container_name: "${PROJECT_NAME}-front"
    ports: 
      - "${PORT}:4200"
    command: bash -c "git clone ${REPO_URL} && cd ${PROJECT_NAME} && npm ci && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - app-network
networks:
  app-network:
    name: ${PROJECT_NAME}-network
    driver: bridge